//
//  MenuModel.swift
//  DesignBase
//
//  Created by lotusprize on 15/4/24.
//  Copyright (c) 2015年 geekTeam. All rights reserved.
//

import Foundation

enum MenuType:Int{
    case CASE = 1, THEORY, METHOD
}

enum CaseTypeList:Int{
    case TIME_SPECIFIC_YEAR = 0, DESIGN_REQUIREMENT, RESEARCH_CLASSIFICATION, USING_OBJECT,MAIN_FIELD
}

enum MethodTypeList:Int{
    case APPLICATION_PHASE = 0, DESIGN_REQUIREMENT, RESEARCH_CLASSIFICATION, USING_OBJECT,MAIN_FIELD
}

enum TheoryCategoryList:Int{
    case CONCEPT_CATEGORY = 0, WHY_WE_NEED_DESIGN_RESEARCH, DEFINITION, ANALYSIS_INTEGRATION,THE_TYPE_OF_DESIGN_RESEARCH, THE_LAYER_OF_DESIGN_RESEARCH,HISTORY_REVOLUTION,EARLY_HISTORY_EXPERIENCE_SUMMARY, BEGINNING_ORIGIN, CONTEMPORARY_DESIGN, THEORETICAL_FOUNDATION,
        BASIC_CONCEPTS, WHAT_IS_DESIGN, HOW_TO_DESIGN, ANOUT_DESIGN_NOUMENON, RATIONAL_PROBLEM_SOLVING_SYSTEM,
        REFLECTED_PRACTICE, INTEGRATED_VIEWS, THEORETICAL_MODEL, OBJECT_MODEL, SYSTEM_MODEL, CHRONOLOGY_SYSTEM, METHODOLOGY_SYSTEM, THEORY_CONSTRUCTION, LOGICAL_ARCUMENT_SYSTEM, BASIC_METHODS, DESIGN_EVALUATION_ETHICS, DESIGN_THE_DESIGN_RESEARCH, RELIABILITY_VALIDITY,ETHICS_MORALITY
}

struct RequestURL{
    static var ServerBookURL:String = "http://121.40.16.252/id_course/id_theory/book/2/chapter/"
    static var ServerMethodURL:String = "http://121.40.16.252/id_course/id_method/category/0/item/0/method/"
    static var ServerCaseURL:String = "http://121.40.16.252/id_course/id_case/"
}